modLoader = "javafml"
loaderVersion = "[36,)"
license = "Code: Public Domain | Assets: Attribution-NonCommercial 4.0 International"
issueTrackerURL = "https://github.com/IriDark/Valoria/issues"
[[mods]]
modId = "valoria"
version = "0.6.3b"
displayName = "Valoria"
updateJSONURL = "https://raw.githubusercontent.com/IriDark/Valoria/refs/heads/main/update.json"
displayURL = "https://discord.gg/wWdXpwuPmK"
logoFile = "Valoria_Logo.png"
credits = "Calamity Mod (sounds)"
authors = "IriDark, Sunday, Kerdo"
description = '''
Valoria — A big RPG themed project that adds some mobs, blocks, weapons, and some bunch of content in "vanilla" texture style
'''
[[dependencies.valoria]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.valoria]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.valoria]]
modId = "curios"
mandatory = true
versionRange = "[5.2.0-beta.3+1.20.1,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.valoria]]
modId = "fluffy_fur"
mandatory = true
versionRange = "[1.20.1-0.1-SNAPSHOT,)"
ordering = "AFTER"
side = "BOTH"
