modLoader = "javafml"
loaderVersion = "[36,)"
license = "Apache-2.0"
issueTrackerURL = "" 
[[mods]] 
  modId = "valoria"
  version = "1.20.1-build-0.6b"
  displayName = "Valoria"
  updateJSONURL="" 
  displayURL = "https://discord.gg/wWdXpwuPmK" 
  logoFile = "Valoria_Logo.png"
  credits = "Calamity Mod (sounds)"
  authors = "IriDark, MaxBogomol"
  description = '''
Valoria — A big RPG themed project that adds some mobs, blocks, weapons, and some bunch of content in "vanilla" texture style
Special Thanks: Ruthenium, .sweetberries, GraFik, It's Cat, Astemir, WOSAJ, Vuzz, Auriny, Arky Fursblack, FoxPlane, Rainach, Feimos.
'''
    [[dependencies.valoria]]
  modId = "forge"
  mandatory = true
  versionRange = "[36,)"
  ordering = "NONE"
  side = "BOTH"
    [[dependencies.valoria]]
		modId = "minecraft"
		mandatory = true
		versionRange = "[1.20.1,1.21)"
		ordering = "NONE"
		side = "BOTH"
    [[dependencies.valoria]]
		modId="curios"
		mandatory=true
		versionRange="[5.2.0-beta.3+1.20.1,)"