blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://discord.gg/wWdXpwuPmK
    about: Questions about the modification should be asked in the Discord, not in the issue tracker. 
  - name: Linktree
    url: https://linktr.ee/iriDark
    about: Misc links. 
